### PR TITLE
Books search, Home screen and Splash changes

### PR DESCRIPTION
**Pull request by EnriqueRZ**
This pull request adds search and some features in Book screen, change images in Splash screen and a first approach in Home screen.

### CODE REVIEW

**Comment by Curicaveri** [comment]
There are several indentation mismatches, this project should have an eslint configuration file with a tab indentation set to 2 or max 4 spaces.

**Review by Curicaveri — CHANGES_REQUESTED** [review]
Please, resolve the indentation mismatches.

**Comment by EnriqueRZ** [comment]
Hello, @Curicaveri, could you check this fixes, please?

**Review by Curicaveri — APPROVED** [review]
There are some other indentation mismatches, but they are ok for now.

**Pull request merged**
